version: "3"
services:
  nginx:
    image: nginx-simple:latest
    container_name: nginx-simple
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./wwwroot/:/var/www/
    build:
      context: .
  php:
    build: ./php
    volumes: 
      - ./wwwroot/:/var/www/
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
  mysqldb:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=password
    volumes:
        - "./data/db/mysql:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
